version: '3.1'

services:
  web:
    image: sample
    ports:
      - 6001:6001

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Soft#2021"
    volumes: 
          - ./init:/docker-entrypoint-initdb.d
          - /home/hr178/sql_data:/var/lib/mysql
